// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: WS2812FX

#ifndef _WS2812FX_UI_H
#define _WS2812FX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ws2812fx
void ui_ws2812fx_screen_init(void);
extern lv_obj_t *ui_ws2812fx;
void ui_event_modeSelect( lv_event_t * e);
extern lv_obj_t *ui_modeSelect;
void ui_event_brightness( lv_event_t * e);
extern lv_obj_t *ui_brightness;
void ui_event_speed( lv_event_t * e);
extern lv_obj_t *ui_speed;
void ui_event_color( lv_event_t * e);
extern lv_obj_t *ui_color;
extern lv_obj_t *ui_presetPanel;
void ui_event_buttonPreset( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset;
extern lv_obj_t *ui_buttonText;
void ui_event_buttonPreset1( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset1;
extern lv_obj_t *ui_buttonText1;
void ui_event_buttonPreset2( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset2;
extern lv_obj_t *ui_buttonText2;
void ui_event_buttonPreset3( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset3;
extern lv_obj_t *ui_buttonText3;
void ui_event_buttonPreset4( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset4;
extern lv_obj_t *ui_buttonText4;
void ui_event_buttonPreset5( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset5;
extern lv_obj_t *ui_buttonText5;
void ui_event_buttonPreset6( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset6;
extern lv_obj_t *ui_buttonText6;
void ui_event_buttonPreset7( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset7;
extern lv_obj_t *ui_buttonText7;
void ui_event_buttonPreset8( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset8;
extern lv_obj_t *ui_buttonText8;
void ui_event_buttonPreset9( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset9;
extern lv_obj_t *ui_buttonText9;
void ui_event_buttonPreset10( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset10;
extern lv_obj_t *ui_buttonText10;
void ui_event_buttonPreset11( lv_event_t * e);
extern lv_obj_t *ui_buttonPreset11;
extern lv_obj_t *ui_buttonText11;
void ui_event_logo( lv_event_t * e);
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_speedText;
extern lv_obj_t *ui_brightnessText;
extern lv_obj_t *ui_modeText;
extern lv_obj_t *ui_presetText;
extern lv_obj_t *ui_colorText;
extern lv_obj_t *ui_infoPanel;
extern lv_obj_t *ui_infoText;
void ui_event_infoButton( lv_event_t * e);
extern lv_obj_t *ui_infoButton;
extern lv_obj_t *ui_infoBtnText;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ws2812fx_png);   // assets/WS2812FX.png


LV_FONT_DECLARE( ui_font_sony16);
LV_FONT_DECLARE( ui_font_sony18);
LV_FONT_DECLARE( ui_font_sony20);
LV_FONT_DECLARE( ui_font_sony80);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
