// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: WS2812FX

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onModeSelect(lv_event_t * e);
void onBrightnessChange(lv_event_t * e);
void onSpeedChange(lv_event_t * e);
void onColorChange(lv_event_t * e);
void onPresetClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
